### ISSUE TITLE
Add CanView permission

### ISSUE THREAD

**Issue by Carl2213** [humhub/tasks#121]
Currently, tasks appear to non-owners in streams and in activities, but clicking on them throws a 401/403 error. This is bad UX.

The only way to fix it is by manually adding `User::USERGROUP_FRIEND`, `User::USERGROUP_USER`, and `User::USERGROUP_GUEST` to each controller of the module.

This is an awful approach because it gets reset on every update.

It's also not great because it's set globally and not on a per-user basis.

A dedicated permission for this would be great. Can also be useful in spaces so that only admins/mods can see tasks.

The permission should also include stream entries and activities, if possible. To avoid the aforementioned bad UX for those without CanView permission.

**Comment by luke-** [comment]
Can you please provide steps to reproduce the error?
What do you mean with "non-owners"?

Visibility permissions for content are very limited. Here we only distinguish from public/private content. 
This is a design decision mainly for performance reasons.

**Comment by buddh4** [comment]
Does this only happens on user profile level?

**Comment by yurabakhtin** [comment]
@luke- I cannot reproduce or don't understand how to reproduce this:

![test_tasks_visibility](https://user-images.githubusercontent.com/6995524/126601697-228d06ad-30c4-4c4f-9e47-cbe58c747186.jpg)

**Comment by luke-** [comment]
I could only find a problem as described here:
https://github.com/humhub/tasks/issues/159

@Carl2213 If your problem still persists, please reopen it and give steps to reproduce it
