### ISSUE TITLE
Checkpoints: Strikethrou 

### ISSUE THREAD

**Issue by luke-** [humhub/tasks#147]
- In the tasks list view, the "strikethrough" feature is not active at all
- In the detail view of a task, the strikethrough is not removed after uncheck
![image](https://user-images.githubusercontent.com/4736168/114744433-fac21c80-9d4d-11eb-84f2-a92ae36b9298.png)

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/tasks/pull/149.

**Comment by luke-** [comment]
@yurabakhtin Thanks!
