### ISSUE TITLE
Public Tasks Issue

### ISSUE THREAD

**Issue by luke-** [humhub/tasks#159]
The Tasks module is currently also displayed in the Space menu for non-members. However, if a non-member clicks on `Tasks`, an 403 error page is displayed. The same problem also affects user profiles.

- This menu item should not appear if a user does not have access to the Tasks module. (/tasks/list)

---

There is also a checkbox to mark a task as "public". Then the task will  show up in the stream also for non-members. However, there is also a "Permission Denied" error here when clicking on  the stream entry.
 
![image](https://user-images.githubusercontent.com/4736168/126629019-dbf6067e-9ef4-4a59-ab42-7dd6b07ddcef.png)

---

Possibilities:

a.) We remove the option for "public" tasks.
b.) We remove the menu entry & the link from the Wall Entry to the Tasks module and show for NonMembers only the Wall Entry without further details.
c.) We allow "Public" access to the Tasks module "/tasks/list".

----

I would prefer solution a.) or b.)

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/tasks/pull/160.
I have implemented the solution b.)
