### ISSUE TITLE
Usability issue with scheduling 

### ISSUE THREAD

**Issue by michaelh99** [humhub/tasks#169]
If you create a Task and check Scheduling without visiting the Scheduling tab and assigning dates, the Hub doesn’t save the task. 
It puts in error text on the scheduling tab but doesn't change focus and so it's not obvious what the problem is.

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/tasks/pull/172.

**Comment by luke-** [comment]
@yurabakhtin Thanks! Please see my PR comment.
