### ISSUE TITLE
PHP Deprecated Warning in ListController.php

### ISSUE THREAD

**Issue by onyxnz** [humhub/tasks#174]
### What steps will reproduce the problem?
In a Space with Tasks enabled, Click Tasks
### What is the expected result?
Form to handle tasks
### What do you get instead?
Crash 
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.9.2
| PHP version      |  8.0.13
| Operating system | Archlinux x64

yii\base\ErrorException: Required parameter $offset follows optional parameter $id in /home/onyx/htdocs/sites/community.freenz.org/protected/modules/tasks/controllers/ListController.php:124
Stack trace:
#0 /home/onyx/htdocs/sites/community.freenz.org/protected/vendor/yiisoft/yii2/BaseYii.php(293): yii\web\ErrorHandler->handleError(code: '...', message: '...', file: '...', line: '...')
humhub/humhub#1 /home/onyx/htdocs/sites/community.freenz.org/protected/vendor/yiisoft/yii2/base/Module.php(643): yii\BaseYii::autoload(className: '...')
humhub/humhub#2 /home/onyx/htdocs/sites/community.freenz.org/protected/vendor/yiisoft/yii2/base/Module.php(643): ::class_exists(class: '...')
humhub/humhub#3 /home/onyx/htdocs/sites/community.freenz.org/protected/vendor/yiisoft/yii2/base/Module.php(602): humhub\modules\tasks\Module->createControllerByID(id: '...')
humhub/humhub#4 /home/onyx/htdocs/sites/community.freenz.org/protected/vendor/yiisoft/yii2/base/Module.php(594): humhub\modules\tasks\Module->createController(route: '...')
humhub/humhub#5 /home/onyx/htdocs/sites/community.freenz.org/protected/vendor/yiisoft/yii2/base/Module.php(528): humhub\components\Application->createController(route: '...')
humhub/humhub#6 /home/onyx/htdocs/sites/community.freenz.org/protected/vendor/yiisoft/yii2/web/Application.php(104): humhub\components\Application->runAction(route: '...', params: '...')
humhub/humhub#7 /home/onyx/htdocs/sites/community.freenz.org/protected/vendor/yiisoft/yii2/base/Application.php(392): humhub\components\Application->handleRequest(request: '...')
humhub/humhub#8 /home/onyx/htdocs/sites/community.freenz.org/index.php(25): humhub\components\Application->run()
humhub/humhub#9 {main}

I am aware that I can turn off these warnings, and this is just my development machine, running very latest PHP; just thought you needed to know.

**Comment by yurabakhtin** [comment]
@luke- @onyxnz I think this issue already was fixed here https://github.com/humhub/tasks/pull/155/files#diff-b174b51f934d851c49936f65f8e045453a52c33b231d12b5d7f79071592c71c2R124

**Comment by luke-** [comment]
@yurabakhtin Thanks!
