### ISSUE TITLE
Error 400 when trying to assign the user for a task

### ISSUE THREAD

**Issue by spwin** [humhub/tasks#179]
There is a bug when assigning a user to the task. Endpoint `/tasks/task/task-assigned-picker` returns error 400 with message about missing id.

**Comment by spwin** [comment]
The following change fixes it:
```
diff --git a/controllers/TaskController.php b/controllers/TaskController.php
index d1e86fb..58e6013 100644
--- a/controllers/TaskController.php
+++ b/controllers/TaskController.php
@@ -107,7 +107,7 @@ class TaskController extends AbstractTaskController
         return $this->asJson(['success' => $task->state->revert($status)]);
     }
 
-    public function actionTaskAssignedPicker($id = null, $keyword = '')
+    public function actionTaskAssignedPicker($keyword = '')
     {
         $query = $this->getSpace()->getMembershipUser();
 
@@ -118,7 +118,7 @@ class TaskController extends AbstractTaskController
         ]));
     }
 
-    public function actionTaskResponsiblePicker($id = null, $keyword = '')
+    public function actionTaskResponsiblePicker($keyword = '')
     {
         $query = $this->getSpace()->getMembershipUser();

```

**Comment by luke-** [comment]
@spwin Thanks for the fix. Can you please provide steps to reproduce?

**Comment by spwin** [comment]
It's happening when creating a new task in a Space and trying to assign a user

![Screenshot from 2022-03-07 21-56-55](https://user-images.githubusercontent.com/11360702/157018629-74e98835-4545-494d-abaa-bc18d3d699b0.png)

**Comment by luke-** [comment]
Hmm, cannot reproduce this, but it's clearly a bug. 
![image](https://user-images.githubusercontent.com/4736168/158056436-a12b4593-301e-455b-8f1a-56a6c8cc9ad8.png)

Thanks!

**Comment by spwin** [comment]
> Hmm, cannot reproduce this, but it's clearly a bug. ![image](https://user-images.githubusercontent.com/4736168/158056436-a12b4593-301e-455b-8f1a-56a6c8cc9ad8.png)
> 
> Thanks!

It’s only happening when running on localhost for me, maybe the validation is disabled on prod or php versions are different. 

Thanks Luke!
