### ISSUE TITLE
Make task clickable in Tasks Overview

### ISSUE THREAD

**Issue by miralita** [humhub/tasks#197]
Please make the task clickable so that you can go to a specific task from the list

**Comment by luke-** [comment]
@miralita Can you be more precise please?

@yurabakhtin Maybe something for: https://github.com/humhub/tasks/pull/189

**Comment by yurabakhtin** [comment]
@luke- Curently when click on the task title from list we load details on the same page:

![task_deatils_from_list](https://user-images.githubusercontent.com/6995524/184589296-9710c30d-afb4-4cf6-9c50-4e3d388f6e23.png)

(this behaviour more related to the PR https://github.com/humhub/tasks/pull/187)

Maybe @miralita wants to open the details in new page like it can be done from wall entry permalink:

![task_details](https://user-images.githubusercontent.com/6995524/184589460-ff4d0fe9-3218-42f4-8e4b-57cd68b3933d.png)

**Comment by miralita** [comment]
In my version of Humhub (1.9.3 CE), there is an error in the console when clicking on the task name. I will recheck the behavior after the update.

```
humhub-bundle.js?v=1643202285:1 Uncaught TypeError: Cannot read properties of undefined (reading 'timeout')
    at Object.redirect (humhub-bundle.js?v=1643202285:1:289391)
    at HTMLLIElement.<anonymous> (humhub.task.search.js?v=1648195906:35:29)
    at HTMLDivElement.dispatch (humhub-app.js?v=1643202266:1:42694)
    at f.handle (humhub-app.js?v=1643202266:1:40691)
redirect	@	humhub-bundle.js?v=1643202285:1
(anonymous)	@	humhub.task.search.js?v=1648195906:35
dispatch	@	humhub-app.js?v=1643202266:1
f.handle	@	humhub-app.js?v=1643202266:1
```

**Comment by miralita** [comment]
The bug is gone in 1.9.4

**Comment by luke-** [comment]
@miralita Thanks for the info!
