### ISSUE TITLE
Theme Colors Not Used

### ISSUE THREAD

**Issue by luke-** [humhub/tasks#203]
![image](https://user-images.githubusercontent.com/4736168/192556810-f8a14460-40f7-4000-8006-6b5ab357b0b4.png)

**Comment by yurabakhtin** [comment]
@luke- Do I understand you correctly the colors should be like primary color of the current themre?
The colors are located in the file https://github.com/humhub/tasks/blob/master/resources/css/task.less#L8, also this file is built to css files manually by command `less`.
So I am not sure how it is possible to make the colors updatable when theme scheme is updated by Theme Builder module.
I.e. the color is static and cannot be dynamic.

**Comment by luke-** [comment]
@yurabakhtin Yes, it's a bit more complicated, unfortunately.

In such cases the colors in modules cannot be used in the Less files.

You have to work either directly in the HTML element with class attributes like "colorPrimary".
Alternatively you can write an inline CSS an use `Yii::$app->view->theme->variable('primary')`.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/tasks/pull/204:

Should we really use primary color? :

![primary-color](https://user-images.githubusercontent.com/6995524/193441911-eb10ac04-4fe1-45c4-92f5-e7d75a5bc678.png)

maybe better use info color? :

![info-color](https://user-images.githubusercontent.com/6995524/193441920-2ad7ae04-e2ed-4100-951a-8a0bf78a1645.png)

**Comment by luke-** [comment]
@yurabakhtin Oh yes, please use the standard color for checkboxes and links

**Comment by yurabakhtin** [comment]
@luke- Commit https://github.com/humhub/tasks/pull/204/commits/647774433d446f549353b4d8ae9035d1ca7d1298:

![colors](https://user-images.githubusercontent.com/6995524/193987632-ce93516a-3cb7-44e6-b2dc-ca4e842f5fbc.png)
