### ISSUE TITLE
Bug- Comment - Upload image not displaying image

### ISSUE THREAD

**Issue by jayavman** [humhub/tasks#231]
Hi @luke-  

When uploading Picture(s) in Task Comment.
![Screenshot 2023-05-09 at 4 04 06 pm](https://user-images.githubusercontent.com/114973646/237008156-8098ebcf-ba0f-4fa1-9a5e-9447cf4593c4.png)

Once posted, If you click on the image, 

![Screenshot 2023-05-09 at 4 04 21 pm](https://user-images.githubusercontent.com/114973646/237008210-41378049-4d26-45db-80da-f65538027113.png)

Task : 1.8.1
Version: 1.14.0
PHP - Version - 8.1.18

**Comment by yurabakhtin** [comment]
@jayavman @luke- I cannot reproduce this on the same versions, probably the problem in the image, it would be good to try other image files.
