### ISSUE TITLE
Duplicate entries in task checklist

### ISSUE THREAD

**Issue by felixhahnweilheim** [humhub/tasks#233]
The checklist items are duplicated after saving the task.

The bug seems similar to this one: https://github.com/humhub/humhub/issues/6344

![Screenshot 2023-05-31 at 20-55-55 Kalender - Family Hub](https://github.com/humhub/tasks/assets/84990763/2e974b17-8bba-4cff-b731-a1924fb21962)

HumHub v1.14.2
Task module v1.8.1

**Comment by luke-** [comment]
@yurabakhtin Can you please take a look?

**Comment by yurabakhtin** [comment]
@felixhahnweilheim @luke- Sorry for the bug, it was fixed here https://github.com/humhub/humhub/issues/6344#issuecomment-1566809468 when we had the same issue in Polls module, I think it will be released in v1.14.3.
