### ISSUE TITLE
Fix Marketplace description and screenshots

### ISSUE THREAD

**Issue by marc-farre** [humhub/tasks#246]
On https://marketplace.humhub.com/module/tasks/description the `docs/README.md` file is not shown.
And there are now screenshots on https://marketplace.humhub.com/module/tasks/screenshots because https://github.com/humhub/tasks/blob/master/module.json#L11 is wrong. It should display the screenshots here: https://github.com/humhub/tasks/tree/master/resources

**Comment by luke-** [comment]
Fixed.
