### ISSUE TITLE
Make the copy/clone function for tasks

### ISSUE THREAD

**Issue by dmitrydrynov** [humhub/tasks#75]
Make the copy function for tasks. I need create one task and clone it for other users.
Thanks )

**Comment by polygon-by** [comment]
I try create a clone function for tasks.
Its work fine but I have problem with copy files for new task. I don't know how do it.
I can find parent task files but don't know how attach this files to a clone task (before save in database).
Help please )

`// 1. Find files for clone task
                $files = $clone_task->fileManager->findAll();
                // 2. Copy files (Upload) for new task
                $files_new = [];
                if(count($files) > 0) foreach($files as $file) {
                    $file_path = $file->getStore()->get();
                    $file_copy_path = $file_path . '_copy';
                    $files_new[] = $file_path;

                    copy($file_path, $file_copy_path);
                    @chmod($file_copy_path, 0744);

                    // ?????
                }`
